# Using R Packages in Python
Going through [this](https://rpy2.github.io/doc/latest/html/introduction.html#getting-started) tutorial.

In [1]:
import rpy2
import numpy as np
import pandas as pd

In [2]:
print(rpy2.__version__)

2.9.4

In [3]:
from rpy2.robjects.packages import importr
import rpy2.robjects.packages as rpackages

# import R's "base" package
base = importr('base')

# import R's "utils" package
utils = importr('utils')

In [4]:
if False:
    # select a mirror for R packages
    utils.chooseCRANmirror(ind=1) # select the first mirror in the list

    # R package names
    packnames = ('ggplot2', 'hexbin')

    # R vector of strings
    from rpy2.robjects.vectors import StrVector

    # Selectively install what needs to be install.
    # We are fancy, just because we can.
    names_to_install = [x for x in packnames if not rpackages.isinstalled(x)]
    if len(names_to_install) > 0:
        utils.install_packages(StrVector(names_to_install))

In [13]:
#utils.install_packages('ggplot2')
#utils.install_packages('hexbin')
from rpy2.robjects.packages import importr
utils.install_packages('DESeq2')

rpy2.rinterface.NULL

In [15]:
deseq = importr('DESeq2')

RRuntimeError: Error in loadNamespace(name) : there is no package called ‘DESeq2’

In [6]:
strpVector = utils.getCRANmirrors()

In [8]:
strpVector

R object with classes: ('data.frame',) mapped to:
<DataFrame - Python:0x7fca812cdcc8 / R:0x5609852b0558>
[StrVector, StrVector, StrVector, StrVector, ..., StrVector, IntVector, StrVector, StrVector]
  Name: <class 'rpy2.robjects.vectors.StrVector'>
  R object with classes: ('character',) mapped to:
<StrVector - Python:0x7fca6c966ec8 / R:0x5609819b1f70>
['0-Cloud ..., '0-Cloud', 'Algeria ..., 'Algeria', ..., 'USA (TX ..., 'USA (TX ..., 'Uruguay ..., 'Venezuela']
  Country: <class 'rpy2.robjects.vectors.StrVector'>
  R object with classes: ('character',) mapped to:
<StrVector - Python:0x7fca6c9d2dc8 / R:0x560981691f60>
['0-Cloud', '0-Cloud', 'Algeria', 'Algeria', ..., 'USA', 'USA', 'Uruguay', 'Venezuela']
  City: <class 'rpy2.robjects.vectors.StrVector'>
  R object with classes: ('character',) mapped to:
<StrVector - Python:0x7fca81950c48 / R:0x560980dfb070>
['0-Cloud', '0-Cloud', 'Algiers', 'Algiers', ..., 'Dallas', 'Dallas', 'Montevid..., 'Valencia']
  URL: <class 'rpy2.robjects.vectors.StrVector'>
  R object with classes: ('character',) mapped to:
<StrVector - Python:0x7fca6c966d88 / R:0x56097ef4f830>
['https://..., 'http://c..., 'https://..., 'http://c..., ..., 'https://..., 'http://c..., 'https://..., 'http://c...]
  Host: <class 'rpy2.robjects.vectors.StrVector'>
  R object with classes: ('character',) mapped to:
<StrVector - Python:0x7fca6c873248 / R:0x56097e485560>
['Automati..., 'Automati..., 'Universi..., 'Universi..., ..., 'Revoluti..., 'Revoluti..., 'Facultad..., 'Universi...]
  Maintainer: <class 'rpy2.robjects.vectors.StrVector'>
  R object with classes: ('character',) mapped to:
<StrVector - Python:0x7fca6c873608 / R:0x56097f9f7290>
['winston ..., 'winston ..., 'Boukala ..., 'Boukala ..., ..., 'David Sm..., 'David Sm..., 'root # f..., 'dir-imyc...]
  OK: <class 'rpy2.robjects.vectors.IntVector'>
  R object with classes: ('integer',) mapped to:
<IntVector - Python:0x7fca6c873788 / R:0x5609812204b0>
[1, 1, 1, 1, ..., 1, 1, 1, 1]
  CountryCode: <class 'rpy2.robjects.vectors.StrVector'>
  R object with classes: ('character',) mapped to:
<StrVector - Python:0x7fca6c873888 / R:0x5609801dab50>
['us', 'us', 'dz', 'dz', ..., 'us', 'us', 'uy', 've']
  Comment: <class 'rpy2.robjects.vectors.StrVector'>
  R object with classes: ('character',) mapped to:
<StrVector - Python:0x7fca6c873988 / R:0x5609817d3520>
['secure_m..., 'secure_m..., 'secure_m..., 'secure_m..., ..., 'secure_m..., 'secure_m..., 'secure_m..., '']

In [ ]:
strpVector

In [ ]:
df = pd.DataFrame(arr)
df.T.head()